Feature/credential reward
Gateway-DAO/gateway-web pull request #138
Opened 2022-04-01 17:35 UTC by agile-fan430

Modified credential reward page.

2022-04-01 18:41 UTC, kbooz requested changes

2022-04-01 18:41 UTC, kbooz commented on src/pages/Gate/pages/GateSuccessPage/style.jsx
> +		margin-top: 52px;
- remove comment
- mixed tabs w/ space

2022-04-01 18:41 UTC, kbooz commented on src/pages/Gate/pages/GateSuccessPage/style.jsx
> +    border-radius: 20px; */
- remove comment
- mixed tabs w/ space

2022-04-01 18:41 UTC, kbooz commented on src/pages/Gate/pages/GateSuccessPage/index.jsx
> +      window.location.href = `/gate/${gateData.id}/`;
This will crash, we're trying to get a property of undefined

2022-04-01 18:41 UTC, kbooz commented on src/pages/Gate/pages/GateSuccessPage/index.jsx
> +    // const clear = setTimeout(() => {
remove comment

2022-04-01 18:41 UTC, kbooz commented on src/pages/Gate/pages/GateSuccessPage/index.jsx
> +          href="https://staging.mygateway.xyz/profile/"
shouldn't it be better a relative url?

2022-04-01 19:39 UTC, kbooz requested changes

2022-04-01 19:39 UTC, kbooz commented on src/pages/Gate/pages/GateSuccessPage/index.jsx
> +          onClick={() => navigate('/profile')}
it's an anchor tag, change it to `href="/profile"`

2022-04-01 19:50 UTC, agile-fan430 commented on src/pages/Gate/pages/GateSuccessPage/index.jsx
> +          onClick={() => navigate('/profile')}
Changed

2022-04-01 23:57 UTC, kbooz approved these changes

2022-04-04 20:23 UTC, NunoMartins21 requested changes
Hey @agile-fan430, take a look on this feedback. These things need to get fixed before approving the PR.

2022-04-04 20:23 UTC, NunoMartins21 commented on src/pages/Gate/pages/GateSuccessPage/index.jsx
> +      <CTAStyled.RbTwo />
I feel like this implementation is overall... weird. In the sense of implementing the animations, I mean. It's not as clear as the `Home` page, and we also are cutting off some images with the margins.

I recommend you following more closely Primoz's approach on the `Home` page, mainly the `Styled.MainBox` component that he is using to encapsulate both `Styled.SpaceBox` and the particles.

Let me know if you have any questions here.

2022-04-05 00:51 UTC, agile-fan430 commented on src/pages/Gate/pages/GateSuccessPage/index.jsx
> +          src={gateData.dao.backgroundURL}
I have changed. pls check

2022-04-05 00:52 UTC, agile-fan430 commented on src/pages/Gate/pages/GateSuccessPage/index.jsx
> +      <CTAStyled.RbTwo />
I have changed.

2022-04-05 18:49 UTC, NunoMartins21 approved these changes
Nicely done! I took the liberty of adding a `border-radius: 100%` on the DAO logo, as I forgot to mention that.

2022-04-05 18:49 UTC, merged