updates code for profile workflow
Gateway-DAO/gateway-web pull request #147
Opened 2022-04-07 17:27 UTC by agile-fan430

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202086331093331

2022-04-07 21:33 UTC, NunoMartins21 requested changes
Hey @agile-fan430, please check my comments here.

2022-04-07 21:33 UTC, NunoMartins21 commented on src/pages/Home/index.jsx
> +    }
This is not the logic that we want. You're checking whether a wallet is active, so you can trigger the navigation, when you should be checking if the user is or isn't initialized (by checking `userInfo.init`).

Also, this snippet of code should be "encapsulated" inside an `useEffect` hook that gets triggered every time the `userInfo` changes, as we need to know when we're changing users.

But perhaps the most important thing of all is: *why* are we putting this piece of code at `Home`? This is a behavior that should be happening on a larger scale, across all the website. A better place to check whether a user is or isn't `init` is on `src/contexts/UserContext.js`, on the `useEffect` we're using to get user information (lines 307-397).

Let me know if you need more information on what you should do here.

2022-04-07 21:33 UTC, NunoMartins21 commented on src/pages/ProfilePage/components/completeProfile/index.tsx
> +		userBio: userInfo?.bio || 'headline',
Why? We don't need to show "headline" as default. If the user doesn't insert a headline, no worries. It isn't mandatory.

2022-04-08 19:37 UTC, agile-fan430 commented
I have changed all. Pls check

2022-04-11 09:53 UTC, agile-fan430 commented on src/pages/Home/index.jsx
> +    }
Because it was impossible to implement the Router in UserContext.js file.

2022-04-11 14:54 UTC, NunoMartins21 requested changes
Hey @agile-fan430, it's way better now. However, I've marked you on a few things to change still. Can you take care of them before I push this?

2022-04-11 14:54 UTC, NunoMartins21 commented on src/contexts/UserContext.js
> +        }
We don't want this. I mean, if the user is initialized, then there's no need for them to get redirected to their profiles every time they connect their wallets.

```suggestion
```

2022-04-11 14:54 UTC, NunoMartins21 commented on src/index.js
> +import { BrowserRouter } from 'react-router-dom';
Please remove these lines, as they're not used anymore.

2022-04-11 14:56 UTC, NunoMartins21 commented on src/index.js
> +import { BrowserRouter } from 'react-router-dom';
Sorry, my mistake. Actually, don't remove the line 27, obviously. Just remove the line 26.

2022-04-11 15:08 UTC, agile-fan430 commented on src/contexts/UserContext.js
> +        }
Sanket told me that the page should redirect to profile page for the already registered users.
So I considered that case.
If you need to remove it, no problem. :)
I will remove and commit again.

2022-04-11 15:17 UTC, agile-fan430 commented
Nuno. I have changed and pushed. pls check.

2022-04-19 18:51 UTC, NunoMartins21 commented on src/contexts/UserContext.js
> +        }
Hey, I was checking this with Sanket. Let's not have this. I noticed you removed it, so I'm just going to accept.

2022-05-03 11:15 UTC, NunoMartins21 approved these changes
Sorry, I took some time to pick this up. In any case, this looks really good and works based on my tests. Nicely done. Approved and merged.

2022-05-03 11:15 UTC, merged